# Generated by Django 4.1.2 on 2022-12-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tookdak', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tookdak',
            old_name='title',
            new_name='file_name',
        ),
        migrations.RemoveField(
            model_name='tookdak',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='tookdak',
            name='body',
        ),
        migrations.AddField(
            model_name='tookdak',
            name='hour',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tookdak',
            name='min',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tookdak',
            name='sec',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
